name: rohm
channels:
  - bottler
  - iopath
  - fvcore
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
#  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - colorama=0.4.4
  - cudatoolkit=10.2.89
  - cython=0.29.28
  - ffmpeg=4.3
  - freetype=2.10.4
  - fvcore=0.1.5.post20210915
#  - gmp=6.2.1
#  - gnutls=3.6.13
#  - intel-openmp=2022.0.1
  - iopath=0.1.9
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
#  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
#  - libgcc-ng=11.2.0
#  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
#  - libnsl=2.0.0
  - libpng=1.6.37
#  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
#  - libuuid=2.32.1
  - libuv=1.43.0
  - libwebp-base=1.2.2
  - libzlib=1.2.11
  - lz4-c=1.9.3
#  - mkl=2022.0.1
#  - ncurses=6.3
#  - nettle=3.6
  - ninja=1.10.2
  - numpy=1.22.3
#  - nvidiacub=1.10.0
  - olefile=0.46
#  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.2
  - pip=22.0.4
  - portalocker=2.4.0
  - python=3.8.13
  - python_abi=3.8
  - pytorch=1.9.1
  - pyyaml=6.0
#  - readline=8.1
  - setuptools=69.1.0
  - sqlite=3.38.2
  - tabulate=0.8.9
  - termcolor=1.1.0
  - tk=8.6.12
  - torchvision=0.10.1
  - tqdm=4.64.0
  - typing_extensions=4.2.0
  - wheel=0.37.1
  - xz=5.2.5
  - yacs=0.1.8
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==1.0.0
    - addict==2.4.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - anyio==3.6.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - async-timeout==4.0.2
    - attrs==21.4.0
    - babel==2.10.1
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - blobfile==2.1.1
    - cachetools==5.0.0
    - certifi==2021.10.8
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - chumpy==0.70
    - configargparse==1.5.3
    - configer==1.3.1
    - configparser==5.2.0
    - cycler==0.11.0
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - einops==0.7.0
    - entrypoints==0.4
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - filelock==3.13.1
    - fonttools==4.33.3
    - freetype-py==2.2.0
    - frozenlist==1.3.0
    - fsspec==2022.3.0
    - future==0.18.2
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - gputil==1.4.0
    - grpcio==1.44.0
    - idna==3.3
    - imageio==2.17.0
    - importlib-metadata==4.11.3
    - importlib-resources==5.7.1
    - ipykernel==6.13.0
    - ipython==8.3.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - json5==0.9.8
    - jsonschema==4.5.1
    - jupyter-client==7.3.1
    - jupyter-core==4.10.0
    - jupyter-packaging==0.12.0
    - jupyter-server==1.17.0
    - jupyterlab==3.4.2
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.13.0
    - jupyterlab-widgets==1.1.0
    - kiwisolver==1.4.2
    - kornia==0.6.5
    - lxml==4.9.4
    - markdown==3.3.6
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - multidict==6.0.2
    - nbclassic==0.3.7
    - nbclient==0.6.3
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - networkx==2.8
    - notebook==6.4.11
    - notebook-shim==0.1.0
    - oauthlib==3.2.0
    - open3d==0.15.2
    - opencv-python==4.5.5.64
    - packaging==21.3
    - pandas==1.4.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.1.0
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.29
    - protobuf==3.20.1
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pycryptodomex==3.20.0
    - pydeprecate==0.3.2
    - pyglet==1.5.23
    - pygments==2.12.0
    - pyopengl==3.1.0
    - pyopengl-accelerate==3.1.5
    - pyparsing==3.0.8
    - pyquaternion==0.9.9
    - pyrender==0.1.45
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pywavelets==1.3.0
    - pyzmq==22.3.0
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-image==0.19.2
    - scikit-learn==1.1.0
    - scipy==1.8.0
    - send2trash==1.8.0
    - six==1.16.0
    - smplx==0.1.28
    - sniffio==1.2.0
    - soupsieve==2.3.2.post1
    - stack-data==0.2.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5
    - terminado==0.13.3
    - test-tube==0.7.5
    - threadpoolctl==3.1.0
    - tifffile==2022.4.22
    - tinycss2==1.1.1
    - tomlkit==0.10.2
    - torchgeometry==0.1.2
    - torchmetrics==0.8.0
    - tornado==6.1
    - traitlets==5.2.0
    - trimesh==3.10.8
    - umnn==1.68
    - urllib3==1.26.9
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.2
    - werkzeug==2.1.1
    - widgetsnbextension==3.6.0
    - yarl==1.7.2
    - zipp==3.8.0
